source = colors.conf
general {
    hide_cursor = true
    ignore_empty_input = true
    immediate_render = true
}

background {
    monitor =
    path = screenshot
    color = $surface
    blur_passes = 2
    blur_size = 4
    brightness = .3
}

image {
    monitor = 
    path = $HOME/.config/hypr/img/pibble.webp
    size = 300
    position = 0, 250
    border_size = 0
}


input-field {
    monitor = 
    size = 400, 90
    outline_thickness = 4
    outer_color = $outline
    inner_color = $primary_container
    font_color = $on_primary
    font_family = JetBrains Mono Nerd Font Propo 16
    fade_on_empty = true
    fail_color = $error
    check_color = $secondary
    check_text = "Authenticating..."
}
