general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
    timeout = 150
    on-timeout = qs ipc call hyprsunsetIpc screenDim
    on-resume = qs ipc call hyprsunsetIpc screenBright
}

listener {
    timeout = 300
    on-timeout = loginctl lock-session
    on-timeout = hyprlock
}

listener {
    timeout = 330
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable"})'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable"})'
}

listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
