# --- Main Colors ---
background            #000000
foreground            #ebdfe6
cursor                #ebdfe6
cursor_text_color     #000000

selection_background  #544151
selection_foreground  #f7daef

url_color             #f5b8a8

# --- ANSI Colors ---
color0                #000000
color1                #ffb4ab
color2                #f5b8a8
color3                #dabfd3
color4                #f0b3e7
color5                #f5b8a8
color6                #dabfd3
color7                #ebdfe6

color8                #4e444b
color9                #93000a
color10               #663c30
color11               #544151
color12               #653661
color13               #544151
color14               #663c30
color15               #d1c3cb

# --- Starship Prompt Bubbles ---
color255              #653661
color254              #f0b3e7
color253              #544151
color252              #dabfd3
color251              #663c30
color250              #f5b8a8
color249              #93000a
color248              #ffb4ab

color232              #ffd7f6
color233              #4c1f49
color234              #f7daef
color235              #3d2b3a
color236              #ffdbd1
color237              #4c261b
color238              #ffdad6
color239              #690005
color240              #ffd7f6

# Matched with unthemed light/dark
color243              #f0b3e7
color244              #ffb4ab
color245              #4e444b

# --- UI Elements ---
active_tab_foreground   #4c1f49
active_tab_background   #f0b3e7
inactive_tab_foreground #ffd7f6
inactive_tab_background #653661

active_border_color     #f0b3e7
inactive_border_color   #9a8d95

# --- Marks ---
mark1_foreground        #330833
mark1_background        #ffd7f6
mark2_foreground        #261624
mark2_background        #f7daef
mark3_foreground        #321208
mark3_background        #ffdbd1